[workspace]

members = [
"xps-gateway"
]

exclude = [ ]

# Make the feature resolver explicit.
# See https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html#details
resolver = "2"
