[package]
name = "localnet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers.workspace = true
anyhow.workspace = true
tokio.workspace = true
ctrlc = "3.4.2"
lib-didethresolver.workspace = true
hex.workspace = true
